[package]
name = "jail"
version = "0.1.0"
authors = ["lolczak <lukasz.jan.olczak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "jail"

[dependencies]
#syscall = "0.2.1"